import { readFileSync } from 'node:fs'
import { join, resolve } from 'node:path'
import { describe, expect, it } from 'vitest'
import { OUTPUT, SOURCE, generate, loadSource, validate } from '../../../scripts/build-icons.ts'
import { iconNames as exportedIconNames } from '../../index.ts'
import { iconNames, iconPaths } from './paths.ts'

const packageRoot = resolve(import.meta.dirname, '../../..')
const repoRoot = resolve(packageRoot, '..', '..')

describe('icon generator', () => {
  it('writes the committed paths.ts, so CI can fail on a stale file', async () => {
    const committed = readFileSync(join(packageRoot, OUTPUT), 'utf8')

    expect(generate(await loadSource(repoRoot))).toBe(committed)
  })

  it('names the source in the header and ends the file with a newline', async () => {
    const text = generate(await loadSource(repoRoot))

    expect(text.split('\n', 1)[0]).toBe(`// Generated by scripts/build-icons.ts from ${SOURCE}. Do not edit by hand.`)
    expect(text.endsWith('\n')).toBe(true)
  })

  it('ships the 23 names and every path of the copy of Resolve, in its order', async () => {
    const source = await loadSource(repoRoot)

    expect(Object.keys(iconPaths)).toHaveLength(23)
    expect(Object.entries(iconPaths)).toEqual(Object.entries(source))
  })

  it('lists in iconNames exactly the names of the table, once each and in its order', () => {
    expect(iconNames).toEqual(Object.keys(iconPaths))
    expect(new Set(iconNames).size).toBe(iconNames.length)
  })

  it('exports iconNames from the package entry point', () => {
    expect(exportedIconNames).toBe(iconNames)
  })

  it('writes iconNames from the icons it is given, so that the list cannot drift from the table', () => {
    const text = generate({ arrow: ['M0 0'], 'arrow-left': ['M1 1'] })

    expect(text).toContain("export const iconNames: readonly IconName[] = [\n  'arrow',\n  'arrow-left',\n]")
  })

  it('is deterministic: the same input gives the same text', async () => {
    const source = await loadSource(repoRoot)

    expect(generate(source)).toBe(generate(structuredClone(source)))
  })

  it('rejects a source that is not an object of icons', () => {
    for (const bad of [undefined, null, {}, 'icons']) expect(() => validate(bad)).toThrow(/at least one icon/)
  })

  it('rejects an icon without paths, with a name that is not lowercase, or with path data it cannot quote', () => {
    expect(() => validate({ arrow: [] })).toThrow(/Icon "arrow" needs at least one path/)
    expect(() => validate({ Arrow: ['M0 0'] })).toThrow(/Icon name "Arrow"/)
    expect(() => validate({ arrow: ["M0 0'"] })).toThrow(/Icon "arrow" has an invalid path/)
  })

  it('quotes a name that is not a plain identifier', () => {
    expect(generate({ 'arrow-left': ['M15 5L8 12L15 19'] })).toContain(
      "  'arrow-left': [\n    'M15 5L8 12L15 19',\n  ],",
    )
  })
})
