// Icon generator: reads Resolve's icon paths and writes the module that `Icon` draws from.
//
//   node --experimental-strip-types --disable-warning=ExperimentalWarning --disable-warning=MODULE_TYPELESS_PACKAGE_JSON \
//     scripts/build-icons.ts
//
// The second warning is switched off because the source lives under design/, outside any package with a `type`.
//
// The source is the verified copy of Resolve's `Icon/paths.ts` (design/resolve-c3f02f8/icon-paths.ts), which is
// never edited. Output (deterministic: source order, fixed formatting, no timestamps):
//   src/components/Icon/paths.ts   `iconPaths`, `IconName` and `iconNames`. Committed; CI regenerates it and fails on any
//                                  diff.
//
// The script sticks to erasable TypeScript, so type stripping can run it (see build-tokens.ts).
import { join, resolve } from 'node:path'
import { pathToFileURL } from 'node:url'
import { isMainModule, write } from './script-utils.ts'

export const SOURCE = 'design/resolve-c3f02f8/icon-paths.ts'
export const OUTPUT = 'src/components/Icon/paths.ts'

export type IconPaths = Record<string, readonly string[]>

// An icon name is a CSS-friendly word, and a path is SVG path data: letters of commands, numbers and separators.
// Anything else would need escaping in the generated string literals, and cannot come from a Figma export.
const NAME = /^[a-z][a-z0-9-]*$/
const PATH_DATA = /^[MmLlHhVvCcSsQqTtAaZz0-9eE.,\s+-]+$/

/** Checks the shape of the source and returns it; throws on the first problem, naming the icon. */
export function validate(source: unknown): IconPaths {
  if (typeof source !== 'object' || source === null || Object.keys(source).length === 0) {
    throw new Error(`${SOURCE} must export \`iconPaths\`, an object with at least one icon`)
  }
  // The result is built entry by entry, so that its type comes from the checks and not from a cast.
  const iconPaths: IconPaths = {}
  for (const [name, paths] of Object.entries(source)) {
    if (!NAME.test(name)) throw new Error(`Icon name "${name}" must be lowercase words joined by "-"`)
    if (!Array.isArray(paths) || paths.length === 0) throw new Error(`Icon "${name}" needs at least one path`)
    const checked: string[] = []
    for (const d of paths) {
      if (typeof d !== 'string' || !PATH_DATA.test(d)) throw new Error(`Icon "${name}" has an invalid path: ${d}`)
      checked.push(d)
    }
    iconPaths[name] = checked
  }
  return iconPaths
}

/** The text of `paths.ts` for these icons. */
export function generate(source: IconPaths): string {
  const iconPaths = validate(source)
  const icons = Object.entries(iconPaths).map(([name, paths]) => {
    const lines = paths.map((d) => `    '${d}',`)
    return `  ${name.includes('-') ? `'${name}'` : name}: [\n${lines.join('\n')}\n  ],`
  })
  return [
    `// Generated by scripts/build-icons.ts from ${SOURCE}. Do not edit by hand.`,
    'export const iconPaths = {',
    ...icons,
    '} as const',
    '',
    'export type IconName = keyof typeof iconPaths',
    '',
    '/** Every icon name, in the order of the table above. */',
    'export const iconNames: readonly IconName[] = [',
    ...Object.keys(iconPaths).map((name) => `  '${name}',`),
    ']',
    '',
  ].join('\n')
}

/** Reads the source icons by importing the module: the file is data in TypeScript syntax, not a format to parse. */
export async function loadSource(repoRoot: string): Promise<IconPaths> {
  const module: { iconPaths?: unknown } = await import(pathToFileURL(join(repoRoot, SOURCE)).href)
  return validate(module.iconPaths)
}

export async function main(root: string, repoRoot = resolve(root, '..', '..')): Promise<void> {
  write(join(root, OUTPUT), generate(await loadSource(repoRoot)))
}

if (isMainModule(import.meta.filename)) {
  try {
    await main(resolve(import.meta.dirname, '..'))
  } catch (error) {
    console.error(error instanceof Error ? error.message : error)
    process.exitCode = 1
  }
}
